### ISSUE TITLE
Consider adding a "safe" variant

### ISSUE THREAD

**Issue by gremo** [webdna/tailwindcss-aspect-ratio#12]
Copy-past SCSS from my projects (this is a safe variant, read more [here](https://css-tricks.com/aspect-ratio-boxes/)):
```scss
// Genera la serie `.ratiobox-{$proportion}`
@each $proportion, $ratio in (
  '16-by-9':   9 / 16,
  '16-by-10': 10 / 16,
  '4-by-3':    3 / 4,
  'square':    1,
) {
  .ratiobox-#{$proportion} {
    &::before {
      @include scut-size(1px 0);

      float: left;
      margin-left: -1px;
      padding-top: $ratio * 100%;
      content: '';
    }

    &::after {
      display: table;
      clear: both;
      content: '';
    }
  }
}
```
